# Generated by Django 2.2.2 on 2020-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200420_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(default='customer', max_length=10),
        ),
    ]
