# Generated by Django 2.2.2 on 2020-04-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200422_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_owner',
        ),
    ]
