# Generated by Django 2.2.2 on 2020-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200421_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
