# Generated by Django 2.2.2 on 2020-04-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_ordered_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_time',
        ),
    ]
